version: '3.3'
services:
  api:
    image: ${IMAGE}
    container_name: money_keeper_api_prd
    restart: on-failure
    command: bash -c "source /app/.env && /bin/money-keeper-backend serve"
    ports:
      - 8080:8080

