version: '3.3'
services:
  api:
    image: ${IMAGE}
    container_name: money_keeper_api_prd
    working_dir: /app
    restart: on-failure
    command: serve
    ports:
      - 8080:8080
    environment:
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8080
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      CIPHER_KEY: ${CIPHER_KEY}
      JWT_HMAC_SECRET: ${JWT_HMAC_SECRET}

