version: '3.3'
services:
  database:
    image: mysql:8
    container_name: money_keeper_database
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
  api:
    image: ${IMAGE}
    container_name: money_keeper_api
    working_dir: /app
    restart: on-failure
    depends_on:
      - database
    command:
      - air
      - -c
      - .air.toml
      - serve
    links:
      - database
    ports:
      - 8080:8080
    volumes:
      - ../../:/app
    environment:
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: money_keeper
      CIPHER_KEY: a78fcb96dcdd64f884add85af738389e40947d75e5f454d106d1afc45cbf1892

volumes:
  database_data: