services:
  database:
    image: mysql:8
    container_name: money_keeper_database
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
  api:
    image: ${IMAGE}
    container_name: money_keeper_api
    working_dir: /app
    restart: on-failure
    depends_on:
      - database
    command:
      - air
      - -c
      - .air.toml
      - serve
    links:
      - database
    ports:
      - 8081:8081
    volumes:
      - ../../:/app
    environment:
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8081
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: money_keeper
      CIPHER_KEY: A78FCB96DCDD64F884ADD85AF738389E40947D75E5F454D106D1AFC45CBF1892
      JWT_HMAC_SECRET: A78FCB96DCDD64F884ADD85AF738389E40947D75E5F454D106D1AFC45CBF1892

volumes:
  database_data:
